name: inference-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - supabase
  - pillow
  - opencv
  - tqdm
  - ffmpeg
  - fastapi>=0.100
  - uvicorn[standard]>=0.23
  - requests
  - pydantic>=2.0
  - python-dotenv
  - aiofiles
  - pip:
      # Install PyTorch with CUDA support, version compatible with CUDA 12.x (runtime in base image)
      - torch==2.1.2
      - torchvision==0.16.2
      - torchaudio==2.1.2
      - transformers>=4.30
      - safetensors>=0.3
