name: inference-env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pillow
  - opencv
  - tqdm
  - ffmpeg
  - fastapi>=0.100
  - uvicorn>=0.23
  - requests
  - httpx
  - pydantic>=1.0
  - python-dotenv
  - aiofiles
  - pip:
      # PyTorch stack (CUDA runtime handled by base image)
      - torch==2.1.2
      - torchvision==0.16.2
      - torchaudio==2.1.2

      # Hugging Face + safetensors
      - transformers>=4.30
      - safetensors>=0.3

      # Supabase client (pip-only)
      - supabase==2.3.5
      - supafunc==0.4.4
